package fr.tyrolium.maxime.init;

import cpw.mods.fml.common.registry.GameRegistry;
import fr.tyrolium.maxime.armor.*;
import net.minecraft.item.Item;

public class ArmorMod {
    public static Item amethys_helmet, amethys_chestplate, amethys_leggings, amethys_boots;
    public static Item aventurine_helmet, aventurine_chestplate, aventurine_leggings, aventurine_boots;
    public static Item copper_helmet, copper_chestplate, copper_leggings, copper_boots;
    public static Item emerald_helmet, emerald_chestplate, emerald_leggings, emerald_boots;
    public static Item ender_helmet, ender_chestplate, ender_leggings, ender_boots;
    public static Item enderine_helmet, enderine_chestplate, enderine_leggings, enderine_boots;
    public static Item flint_helmet, flint_chestplate, flint_leggings, flint_boots;
    public static Item gravel_helmet, gravel_chestplate, gravel_leggings, gravel_boots;
    public static Item guardian_helmet, guardian_chestplate, guardian_leggings, guardian_boots;
    //public static Item oak_helmet, oak_chestplate, oak_leggings, oak_boots;
    public static Item obsidian_helmet, obsidian_chestplate, obsidian_leggings, obsidian_boots;
    public static Item obsidian_red_helmet, obsidian_red_chestplate, obsidian_red_leggings, obsidian_red_boots;
    public static Item purified_gold_helmet, purified_gold_chestplate, purified_gold_leggings, purified_gold_boots;
    public static Item redstone_helmet, redstone_chestplate, redstone_leggings, redstone_boots;
    public static Item rhodonite_helmet, rhodonite_chestplate, rhodonite_leggings, rhodonite_boots;
    public static Item ruby_helmet, ruby_chestplate, ruby_leggings, ruby_boots;
    public static Item sapphire_helmet, sapphire_chestplate, sapphire_leggings, sapphire_boots;
    public static Item stone_helmet, stone_chestplate, stone_leggings, stone_boots;
    public static Item tin_helmet, tin_chestplate, tin_leggings, tin_boots;
    public static Item titane_helmet, titane_chestplate, titane_leggings, titane_boots;
    public static Item tyrolium_helmet, tyrolium_chestplate, tyrolium_leggings, tyrolium_boots;
    public static Item volcanium_helmet, volcanium_chestplate, volcanium_leggings, volcanium_boots;
    public static Item yellorite_helmet, yellorite_chestplate, yellorite_leggings, yellorite_boots;

    public ArmorMod(){
    }

    public static void init() {
        amethys_helmet = new AmethysArmor(0, "amethys_helmet");
        amethys_chestplate = new AmethysArmor(1, "amethys_chestplate");
        amethys_leggings = new AmethysArmor(2, "amethys_leggings");
        amethys_boots = new AmethysArmor(3, "amethys_boots");
        aventurine_helmet = new AventurineArmor(0, "aventurine_helmet");
        aventurine_chestplate = new AventurineArmor(1, "aventurine_chestplate");
        aventurine_leggings = new AventurineArmor(2, "aventurine_leggings");
        aventurine_boots = new AventurineArmor(3, "aventurine_boots");
        copper_helmet = new CopperArmor(0, "copper_helmet");
        copper_chestplate = new CopperArmor(1, "copper_chestplate");
        copper_leggings = new CopperArmor(2, "copper_leggings");
        copper_boots = new CopperArmor(3, "copper_boots");
        emerald_helmet = new EmeraldArmor(0, "emerald_helmet");
        emerald_chestplate = new EmeraldArmor(1, "emerald_chestplate");
        emerald_leggings = new EmeraldArmor(2, "emerald_leggings");
        emerald_boots = new EmeraldArmor(3, "emerald_boots");
        ender_helmet = new EnderArmor(0, "ender_helmet");
        ender_chestplate = new EnderArmor(1, "ender_chestplate");
        ender_leggings = new EnderArmor(2, "ender_leggings");
        ender_boots = new EnderArmor(3, "ender_boots");
        enderine_helmet = new EnderineArmor(0, "enderine_helmet");
        enderine_chestplate = new EnderineArmor(1, "enderine_chestplate");
        enderine_leggings = new EnderineArmor(2, "enderine_leggings");
        enderine_boots = new EnderineArmor(3, "enderine_boots");
        flint_helmet = new FlintArmor(0, "flint_helmet");
        flint_chestplate = new FlintArmor(1, "flint_chestplate");
        flint_leggings = new FlintArmor(2, "flint_leggings");
        flint_boots = new FlintArmor(3, "flint_boots");
        gravel_helmet = new GravelArmor(0, "gravel_helmet");
        gravel_chestplate = new GravelArmor(1, "gravel_chestplate");
        gravel_leggings = new GravelArmor(2, "gravel_leggings");
        gravel_boots = new GravelArmor(3, "gravel_boots");
        guardian_helmet = new GuardianArmor(0, "guardian_helmet");
        guardian_chestplate = new GuardianArmor(1, "guardian_chestplate");
        guardian_leggings = new GuardianArmor(2, "guardian_leggings");
        guardian_boots = new GuardianArmor(3, "guardian_boots");
        obsidian_helmet = new ObsidianArmor(0, "obsidian_helmet");
        obsidian_chestplate = new ObsidianArmor(1, "obsidian_chestplate");
        obsidian_leggings = new ObsidianArmor(2, "obsidian_leggings");
        obsidian_boots = new ObsidianArmor(3, "obsidian_boots");
        obsidian_red_helmet = new ObsidianRedArmor(0, "obsidian_red_helmet");
        obsidian_red_chestplate = new ObsidianRedArmor(1, "obsidian_red_chestplate");
        obsidian_red_leggings = new ObsidianRedArmor(2, "obsidian_red_leggings");
        obsidian_red_boots = new ObsidianRedArmor(3, "obsidian_red_boots");
        purified_gold_helmet = new PurifiedGoldArmor(0, "purified_gold_helmet");
        purified_gold_chestplate = new PurifiedGoldArmor(1, "purified_gold_chestplate");
        purified_gold_leggings = new PurifiedGoldArmor(2, "purified_gold_leggings");
        purified_gold_boots = new PurifiedGoldArmor(3, "purified_gold_boots");
        redstone_helmet = new RedstoneArmor(0, "redstone_helmet");
        redstone_chestplate = new RedstoneArmor(1, "redstone_chestplate");
        redstone_leggings = new RedstoneArmor(2, "redstone_leggings");
        redstone_boots = new RedstoneArmor(3, "redstone_boots");
        rhodonite_helmet = new RhodoniteArmor(0, "rhodonite_helmet");
        rhodonite_chestplate = new RhodoniteArmor(1, "rhodonite_chestplate");
        rhodonite_leggings = new RhodoniteArmor(2, "rhodonite_leggings");
        rhodonite_boots = new RhodoniteArmor(3, "rhodonite_boots");
        ruby_helmet = new RubyArmor(0, "ruby_helmet");
        ruby_chestplate = new RubyArmor(1, "ruby_chestplate");
        ruby_leggings = new RubyArmor(2, "ruby_leggings");
        ruby_boots = new RubyArmor(3, "ruby_boots");
        sapphire_helmet = new SapphireArmor(0, "sapphire_helmet");
        sapphire_chestplate = new SapphireArmor(1, "sapphire_chestplate");
        sapphire_leggings = new SapphireArmor(2, "sapphire_leggings");
        sapphire_boots = new SapphireArmor(3, "sapphire_boots");
        stone_helmet = new StoneArmor(0, "stone_helmet");
        stone_chestplate = new StoneArmor(1, "stone_chestplate");
        stone_leggings = new StoneArmor(2, "stone_leggings");
        stone_boots = new StoneArmor(3, "stone_boots");
        tin_helmet = new TinArmor(0, "tin_helmet");
        tin_chestplate = new TinArmor(1, "tin_chestplate");
        tin_leggings = new TinArmor(2, "tin_leggings");
        tin_boots = new TinArmor(3, "tin_boots");
        titane_helmet = new TitaneArmor(0, "titane_helmet");
        titane_chestplate = new TitaneArmor(1, "titane_chestplate");
        titane_leggings = new TitaneArmor(2, "titane_leggings");
        titane_boots = new TitaneArmor(3, "titane_boots");
        tyrolium_helmet = new TyroliumArmor(0, "tyrolium_helmet");
        tyrolium_chestplate = new TyroliumArmor(1,"tyrolium_chestplate");
        tyrolium_leggings = new TyroliumArmor(2, "tyrolium_leggings");
        tyrolium_boots = new TyroliumArmor(3, "tyrolium_boots");
        volcanium_helmet = new VolcaniumArmor(0, "volcanium_helmet");
        volcanium_chestplate = new VolcaniumArmor(1, "volcanium_chestplate");
        volcanium_leggings = new VolcaniumArmor(2, "volcanium_leggings");
        volcanium_boots = new VolcaniumArmor(3, "volcanium_boots");
        yellorite_helmet = new YelloriteArmor(0, "yellorite_helmet");
        yellorite_chestplate = new YelloriteArmor(1, "yellorite_chestplate");
        yellorite_leggings = new YelloriteArmor(2, "yellorite_leggings");
        yellorite_boots = new YelloriteArmor(3, "yellorite_boots");
    }

    public static void register() {
        GameRegistry.registerItem(amethys_helmet, "amethys_helmet");
        GameRegistry.registerItem(amethys_chestplate, "amethys_chestplate");
        GameRegistry.registerItem(amethys_leggings, "amethys_leggings");
        GameRegistry.registerItem(amethys_boots, "amethys_boots");
        GameRegistry.registerItem(aventurine_helmet, "aventurine_helmet");
        GameRegistry.registerItem(aventurine_chestplate, "aventurine_chestplate");
        GameRegistry.registerItem(aventurine_leggings, "aventurine_leggings");
        GameRegistry.registerItem(aventurine_boots, "aventurine_boots");
        GameRegistry.registerItem(copper_helmet, "copper_helmet");
        GameRegistry.registerItem(copper_chestplate, "copper_chestplate");
        GameRegistry.registerItem(copper_leggings, "copper_leggings");
        GameRegistry.registerItem(copper_boots, "copper_boots");
        GameRegistry.registerItem(emerald_helmet, "emerald_helmet");
        GameRegistry.registerItem(emerald_chestplate, "emerald_chestplate");
        GameRegistry.registerItem(emerald_leggings, "emerald_leggings");
        GameRegistry.registerItem(emerald_boots, "emerald_boots");
        GameRegistry.registerItem(ender_helmet, "ender_helmet");
        GameRegistry.registerItem(ender_chestplate, "ender_chestplate");
        GameRegistry.registerItem(ender_leggings, "ender_leggings");
        GameRegistry.registerItem(ender_boots, "ender_boots");
        GameRegistry.registerItem(enderine_helmet, "enderine_helmet");
        GameRegistry.registerItem(enderine_chestplate, "enderine_chestplate");
        GameRegistry.registerItem(enderine_leggings, "enderine_leggings");
        GameRegistry.registerItem(enderine_boots, "enderine_boots");
        GameRegistry.registerItem(flint_helmet, "flint_helmet");
        GameRegistry.registerItem(flint_chestplate, "flint_chestplate");
        GameRegistry.registerItem(flint_leggings, "flint_leggings");
        GameRegistry.registerItem(flint_boots, "flint_boots");
        GameRegistry.registerItem(gravel_helmet, "gravel_helmet");
        GameRegistry.registerItem(gravel_chestplate, "gravel_chestplate");
        GameRegistry.registerItem(gravel_leggings, "gravel_leggings");
        GameRegistry.registerItem(gravel_boots, "gravel_boots");
        GameRegistry.registerItem(guardian_helmet, "guardian_helmet");
        GameRegistry.registerItem(guardian_chestplate, "guardian_chestplate");
        GameRegistry.registerItem(guardian_leggings, "guardian_leggings");
        GameRegistry.registerItem(guardian_boots, "guardian_boots");
        GameRegistry.registerItem(obsidian_helmet, "obsidian_helmet");
        GameRegistry.registerItem(obsidian_chestplate, "obsidian_chestplate");
        GameRegistry.registerItem(obsidian_leggings, "obsidian_leggings");
        GameRegistry.registerItem(obsidian_boots, "obsidian_boots");
        GameRegistry.registerItem(obsidian_red_helmet, "obsidian_red_helmet");
        GameRegistry.registerItem(obsidian_red_chestplate, "obsidian_red_chestplate");
        GameRegistry.registerItem(obsidian_red_leggings, "obsidian_red_leggings");
        GameRegistry.registerItem(obsidian_red_boots, "obsidian_red_boots");
        GameRegistry.registerItem(purified_gold_helmet, "purified_gold_helmet");
        GameRegistry.registerItem(purified_gold_chestplate, "purified_gold_chestplate");
        GameRegistry.registerItem(purified_gold_leggings, "purified_gold_leggings");
        GameRegistry.registerItem(purified_gold_boots, "purified_gold_boots");
        GameRegistry.registerItem(redstone_helmet, "redstone_helmet");
        GameRegistry.registerItem(redstone_chestplate, "redstone_chestplate");
        GameRegistry.registerItem(redstone_leggings, "redstone_leggings");
        GameRegistry.registerItem(redstone_boots, "redstone_boots");
        GameRegistry.registerItem(rhodonite_helmet, "rhodonite_helmet");
        GameRegistry.registerItem(rhodonite_chestplate, "rhodonite_chestplate");
        GameRegistry.registerItem(rhodonite_leggings, "rhodonite_leggings");
        GameRegistry.registerItem(rhodonite_boots, "rhodonite_boots");
        GameRegistry.registerItem(ruby_helmet, "ruby_helmet");
        GameRegistry.registerItem(ruby_chestplate, "ruby_chestplate");
        GameRegistry.registerItem(ruby_leggings, "ruby_leggings");
        GameRegistry.registerItem(ruby_boots, "ruby_boots");
        GameRegistry.registerItem(sapphire_helmet, "sapphire_helmet");
        GameRegistry.registerItem(sapphire_chestplate, "sapphire_chestplate");
        GameRegistry.registerItem(sapphire_leggings, "sapphire_leggings");
        GameRegistry.registerItem(sapphire_boots, "sapphire_boots");
        GameRegistry.registerItem(stone_helmet, "stone_helmet");
        GameRegistry.registerItem(stone_chestplate, "stone_chestplate");
        GameRegistry.registerItem(stone_leggings, "stone_leggings");
        GameRegistry.registerItem(stone_boots, "stone_boots");
        GameRegistry.registerItem(tin_helmet, "tin_helmet");
        GameRegistry.registerItem(tin_chestplate, "tin_chestplate");
        GameRegistry.registerItem(tin_leggings, "tin_leggings");
        GameRegistry.registerItem(tin_boots, "tin_boots");
        GameRegistry.registerItem(titane_helmet, "titane_helmet");
        GameRegistry.registerItem(titane_chestplate, "titane_chestplate");
        GameRegistry.registerItem(titane_leggings, "titane_leggings");
        GameRegistry.registerItem(titane_boots, "titane_boots");
        GameRegistry.registerItem(tyrolium_helmet, "tyrolium_helmet");
        GameRegistry.registerItem(tyrolium_chestplate, "tyrolium_chestplate");
        GameRegistry.registerItem(tyrolium_leggings, "tyrolium_leggings");
        GameRegistry.registerItem(tyrolium_boots, "tyrolium_boots");
        GameRegistry.registerItem(volcanium_helmet, "volcanium_helmet");
        GameRegistry.registerItem(volcanium_chestplate, "volcanium_chestplate");
        GameRegistry.registerItem(volcanium_leggings, "volcanium_leggings");
        GameRegistry.registerItem(volcanium_boots, "volcanium_boots");
        GameRegistry.registerItem(yellorite_helmet, "yellorite_helmet");
        GameRegistry.registerItem(yellorite_chestplate, "yellorite_chestplate");
        GameRegistry.registerItem(yellorite_leggings, "yellorite_leggings");
        GameRegistry.registerItem(yellorite_boots, "yellorite_boots");
    }
}
